trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - pwsh: Write-Host 'Build succeeds'

- stage: Deploy
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'main'))
  jobs:
  - job: Deploy
    steps:
    - pwsh: Write-Host 'This was expected to deploy from refs/heads/main'
